#!/usr/bin/ash

run_earlyhook() {
    if [ "$quiet" = "y" ] || [ -e "/usr/lib/firmware/bootsplash-themes" ]; then
        log_level=notice
    else
        log_level=info
    fi
    kmod static-nodes --format=tmpfiles --output=/run/tmpfiles.d/kmod.conf
    systemd-tmpfiles --prefix=/dev --create --boot
    SYSTEMD_LOG_LEVEL=$log_level /usr/lib/systemd/systemd-udevd --daemon --resolve-names=never
    udevd_running=1
}

run_hook() {
    msg ":: Triggering uevents..."
    udevadm trigger --action=add --type=subsystems
    udevadm trigger --action=add --type=devices
    udevadm settle
}

run_cleanuphook() {
    udevadm control --exit
    udevadm info --cleanup-db
}

# vim: set ft=sh ts=4 sw=4 et:
